logging.level.root=INFO
logging.level.fonda=INFO
logging.level.cws.k8s.scheduler=DEBUG
logging.level.cws.k8s.rest=DEBUG
logging.level.cws.k8s.client=DEBUG
server.port=8080
server.servlet.context-path=/